### ISSUE TITLE
A bug in display function

### ISSUE THREAD

**Issue by chengwei-xia** [Ahmed-Bayoumy/OMADS#19]
Hi, I met this error below from the display function even if I ran the tutorial example. Now I can only run the code with display=False. 

"Traceback (most recent call last):

  File ~/anaconda3/envs/DeePCfenics/lib/python3.9/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/Documents/DeePC_FlowControl/Main/MADS_test.py:31
    out = POLL.main(data)

  File ~/anaconda3/envs/DeePCfenics/lib/python3.9/site-packages/OMADS/POLL.py:466 in main
    #log.log_msg(msg=" end of orthogonal MADS " + args[1] + " in the internal BM suite.", msg_type=MSG_TYPE.INFO)

IndexError: tuple index out of range"

**Comment by Ahmed-Bayoumy** [comment]
Thank you [chengwei-xia](https://github.com/chengwei-xia) for filing the issue. The fix has now been merged to the DEV branch and a new patch release will be uploaded to both OMADS GitHub repo and PyPi.
